var searchData=
[
  ['safari',['Safari',['../namespace_alexander_on_test_1_1_net_core_web_driver_factory.html#a95eab86bf50d5d39d62f2aae53408c07a50de9bc68c93dc32d8c7c90593471760',1,'AlexanderOnTest::NetCoreWebDriverFactory']]],
  ['serializetojson',['SerializeToJson',['../class_alexander_on_test_1_1_net_core_web_driver_factory_1_1_config_1_1_web_driver_configuration.html#a3c3126d9cefced393071e2fe3580bbd4',1,'AlexanderOnTest::NetCoreWebDriverFactory::Config::WebDriverConfiguration']]],
  ['seriloglogprovider',['SerilogLogProvider',['../class_alexander_on_test_1_1_web_driver_factory_nunit_config_1_1_logging_1_1_log_providers_1_1_serilog_log_provider.html',1,'AlexanderOnTest.WebDriverFactoryNunitConfig.Logging.LogProviders.SerilogLogProvider'],['../class_alexander_on_test_1_1_net_core_web_driver_factory_1_1_logging_1_1_log_providers_1_1_serilog_log_provider.html',1,'AlexanderOnTest.NetCoreWebDriverFactory.Logging.LogProviders.SerilogLogProvider']]],
  ['servicecollectionfactory',['ServiceCollectionFactory',['../class_alexander_on_test_1_1_net_core_web_driver_factory_1_1_dependency_injection_1_1_service_collection_factory.html',1,'AlexanderOnTest::NetCoreWebDriverFactory::DependencyInjection']]],
  ['setcurrentlogprovider',['SetCurrentLogProvider',['../class_alexander_on_test_1_1_net_core_web_driver_factory_1_1_logging_1_1_log_provider.html#ac8a5b7eaa1bef6bc828954269ec322d4',1,'AlexanderOnTest.NetCoreWebDriverFactory.Logging.LogProvider.SetCurrentLogProvider()'],['../class_alexander_on_test_1_1_web_driver_factory_nunit_config_1_1_logging_1_1_log_provider.html#ae7bb804941b43aa42613e2f888de7666',1,'AlexanderOnTest.WebDriverFactoryNunitConfig.Logging.LogProvider.SetCurrentLogProvider()']]],
  ['setplatform_3c_20t_20_3e',['SetPlatform&lt; T &gt;',['../class_alexander_on_test_1_1_net_core_web_driver_factory_1_1_driver_options_factory_1_1_default_driver_options_factory.html#a9c2d59b03fd8f93c3198b0f0ab79b55b',1,'AlexanderOnTest.NetCoreWebDriverFactory.DriverOptionsFactory.DefaultDriverOptionsFactory.SetPlatform&lt; T &gt;()'],['../class_alexander_on_test_1_1_net_core_web_driver_factory_1_1_driver_options_factory_1_1_static_driver_options_factory.html#a8327ef7a54ca49908437b5d6c24d7b8a',1,'AlexanderOnTest.NetCoreWebDriverFactory.DriverOptionsFactory.StaticDriverOptionsFactory.SetPlatform&lt; T &gt;()']]],
  ['setwindowsize',['SetWindowSize',['../interface_alexander_on_test_1_1_net_core_web_driver_factory_1_1_utils_1_1_i_web_driver_re_sizer.html#a1627f119d897e8419b25e3ead5159817',1,'AlexanderOnTest.NetCoreWebDriverFactory.Utils.IWebDriverReSizer.SetWindowSize()'],['../class_alexander_on_test_1_1_net_core_web_driver_factory_1_1_utils_1_1_web_driver_re_sizer.html#a54b76183d4ebaa6444d574bbfac54849',1,'AlexanderOnTest.NetCoreWebDriverFactory.Utils.WebDriverReSizer.SetWindowSize()']]],
  ['simulatestructuredlogging',['SimulateStructuredLogging',['../class_alexander_on_test_1_1_net_core_web_driver_factory_1_1_logging_1_1_log_providers_1_1_log_message_formatter.html#a0347f7acc09c70b67925ee52fbb1a014',1,'AlexanderOnTest.NetCoreWebDriverFactory.Logging.LogProviders.LogMessageFormatter.SimulateStructuredLogging()'],['../class_alexander_on_test_1_1_web_driver_factory_nunit_config_1_1_logging_1_1_log_providers_1_1_log_message_formatter.html#a763976bea6dd43bd37ceb385ff2f292c',1,'AlexanderOnTest.WebDriverFactoryNunitConfig.Logging.LogProviders.LogMessageFormatter.SimulateStructuredLogging()']]],
  ['size',['Size',['../class_alexander_on_test_1_1_net_core_web_driver_factory_1_1_window_size_extension.html#ae4bc29740defba94c7f783a299b0d97d',1,'AlexanderOnTest::NetCoreWebDriverFactory::WindowSizeExtension']]],
  ['sizejsonconverter',['SizeJsonConverter',['../class_alexander_on_test_1_1_net_core_web_driver_factory_1_1_utils_1_1_converters_1_1_size_json_converter.html',1,'AlexanderOnTest::NetCoreWebDriverFactory::Utils::Converters']]],
  ['start',['Start',['../class_alexander_on_test_1_1_net_core_web_driver_factory_1_1_utils_1_1_builders_1_1_web_driver_configuration_builder.html#a9763b6b1d0d5ea6367f6cbd42dd2fe32',1,'AlexanderOnTest::NetCoreWebDriverFactory::Utils::Builders::WebDriverConfigurationBuilder']]],
  ['staticdriveroptionsfactory',['StaticDriverOptionsFactory',['../class_alexander_on_test_1_1_net_core_web_driver_factory_1_1_driver_options_factory_1_1_static_driver_options_factory.html',1,'AlexanderOnTest::NetCoreWebDriverFactory::DriverOptionsFactory']]]
];
