var searchData=
[
  ['warn',['Warn',['../class_alexander_on_test_1_1_net_core_web_driver_factory_1_1_logging_1_1_log_extensions.html#a214b568381de925bbadec2810865183f',1,'AlexanderOnTest.NetCoreWebDriverFactory.Logging.LogExtensions.Warn(this ILog logger, Func&lt; string &gt; messageFunc)'],['../class_alexander_on_test_1_1_net_core_web_driver_factory_1_1_logging_1_1_log_extensions.html#ad1c69418bdf3d7672ca83a8a34d0d95a',1,'AlexanderOnTest.NetCoreWebDriverFactory.Logging.LogExtensions.Warn(this ILog logger, string message)'],['../class_alexander_on_test_1_1_net_core_web_driver_factory_1_1_logging_1_1_log_extensions.html#aada2903eb468f889b3f975328e65d7dc',1,'AlexanderOnTest.NetCoreWebDriverFactory.Logging.LogExtensions.Warn(this ILog logger, string message, params object[] args)'],['../class_alexander_on_test_1_1_net_core_web_driver_factory_1_1_logging_1_1_log_extensions.html#afaab61ac7c03ec85ec048c9cb7bbce48',1,'AlexanderOnTest.NetCoreWebDriverFactory.Logging.LogExtensions.Warn(this ILog logger, Exception exception, string message, params object[] args)'],['../class_alexander_on_test_1_1_web_driver_factory_nunit_config_1_1_logging_1_1_log_extensions.html#aa51427cd435c3d510f1c5a9c0768afd3',1,'AlexanderOnTest.WebDriverFactoryNunitConfig.Logging.LogExtensions.Warn(this ILog logger, Func&lt; string &gt; messageFunc)'],['../class_alexander_on_test_1_1_web_driver_factory_nunit_config_1_1_logging_1_1_log_extensions.html#a0329f4740134b1994e2e679e52b5053b',1,'AlexanderOnTest.WebDriverFactoryNunitConfig.Logging.LogExtensions.Warn(this ILog logger, string message)'],['../class_alexander_on_test_1_1_web_driver_factory_nunit_config_1_1_logging_1_1_log_extensions.html#ac2b744d7a9b14551c975ea7447dc3e0e',1,'AlexanderOnTest.WebDriverFactoryNunitConfig.Logging.LogExtensions.Warn(this ILog logger, string message, params object[] args)'],['../class_alexander_on_test_1_1_web_driver_factory_nunit_config_1_1_logging_1_1_log_extensions.html#a24c8640aa2c8044091fc6619d7325f04',1,'AlexanderOnTest.WebDriverFactoryNunitConfig.Logging.LogExtensions.Warn(this ILog logger, Exception exception, string message, params object[] args)'],['../namespace_alexander_on_test_1_1_net_core_web_driver_factory_1_1_logging.html#a20c7e594d60734f72bb4dd0aab7e4f5aa56525ae64d370c0b448ac0d60710ef17',1,'AlexanderOnTest.NetCoreWebDriverFactory.Logging.Warn()'],['../namespace_alexander_on_test_1_1_web_driver_factory_nunit_config_1_1_logging.html#adb06089509dc69c0a431989d1c363e23a56525ae64d370c0b448ac0d60710ef17',1,'AlexanderOnTest.WebDriverFactoryNunitConfig.Logging.Warn()']]],
  ['warnexception',['WarnException',['../class_alexander_on_test_1_1_net_core_web_driver_factory_1_1_logging_1_1_log_extensions.html#acc243c65a726e4166679589cc06b5be5',1,'AlexanderOnTest.NetCoreWebDriverFactory.Logging.LogExtensions.WarnException()'],['../class_alexander_on_test_1_1_web_driver_factory_nunit_config_1_1_logging_1_1_log_extensions.html#ab4c604c9277c16bbcc4997b4888790a4',1,'AlexanderOnTest.WebDriverFactoryNunitConfig.Logging.LogExtensions.WarnException()']]],
  ['warnformat',['WarnFormat',['../class_alexander_on_test_1_1_net_core_web_driver_factory_1_1_logging_1_1_log_extensions.html#af460fcfb74b4524525f4f592bb2e39d2',1,'AlexanderOnTest.NetCoreWebDriverFactory.Logging.LogExtensions.WarnFormat()'],['../class_alexander_on_test_1_1_web_driver_factory_nunit_config_1_1_logging_1_1_log_extensions.html#a6bcb634f16c7c83a6769c0ad4344fa1f',1,'AlexanderOnTest.WebDriverFactoryNunitConfig.Logging.LogExtensions.WarnFormat()']]],
  ['webdriverconfiguration',['WebDriverConfiguration',['../class_alexander_on_test_1_1_net_core_web_driver_factory_1_1_config_1_1_web_driver_configuration.html',1,'AlexanderOnTest.NetCoreWebDriverFactory.Config.WebDriverConfiguration'],['../class_alexander_on_test_1_1_web_driver_factory_nunit_config_1_1_test_settings_1_1_web_driver_settings.html#ac12683c0cabeb2b0338cdea5b091d7d8',1,'AlexanderOnTest.WebDriverFactoryNunitConfig.TestSettings.WebDriverSettings.WebDriverConfiguration()'],['../class_alexander_on_test_1_1_net_core_web_driver_factory_1_1_config_1_1_web_driver_configuration.html#acd71dd43c2813222a603e3ab8f99a071',1,'AlexanderOnTest.NetCoreWebDriverFactory.Config.WebDriverConfiguration.WebDriverConfiguration()']]],
  ['webdriverconfigurationbuilder',['WebDriverConfigurationBuilder',['../class_alexander_on_test_1_1_net_core_web_driver_factory_1_1_utils_1_1_builders_1_1_web_driver_configuration_builder.html',1,'AlexanderOnTest::NetCoreWebDriverFactory::Utils::Builders']]],
  ['webdrivermanager',['WebDriverManager',['../class_alexander_on_test_1_1_net_core_web_driver_factory_1_1_driver_manager_1_1_web_driver_manager.html',1,'AlexanderOnTest.NetCoreWebDriverFactory.DriverManager.WebDriverManager'],['../class_alexander_on_test_1_1_net_core_web_driver_factory_1_1_driver_manager_1_1_web_driver_manager.html#a6f66790a35031b785bd893eec550e524',1,'AlexanderOnTest.NetCoreWebDriverFactory.DriverManager.WebDriverManager.WebDriverManager(IWebDriverFactory factory, IWebDriverConfiguration configuration)'],['../class_alexander_on_test_1_1_net_core_web_driver_factory_1_1_driver_manager_1_1_web_driver_manager.html#add960698db3fda41380240362d057fa6',1,'AlexanderOnTest.NetCoreWebDriverFactory.DriverManager.WebDriverManager.WebDriverManager(IWebDriverFactory factory, Browser browser, WindowSize windowSize=WindowSize.Hd, bool isLocal=true, PlatformType platformType=PlatformType.Any, bool headless=false)']]],
  ['webdriverresizer',['WebDriverReSizer',['../class_alexander_on_test_1_1_net_core_web_driver_factory_1_1_utils_1_1_web_driver_re_sizer.html',1,'AlexanderOnTest.NetCoreWebDriverFactory.Utils.WebDriverReSizer'],['../class_alexander_on_test_1_1_net_core_web_driver_factory_1_1_web_driver_factory_1_1_local_web_driver_factory_base.html#a605f2a814ef60d95f730aff90fd9aa7a',1,'AlexanderOnTest.NetCoreWebDriverFactory.WebDriverFactory.LocalWebDriverFactoryBase.WebDriverReSizer()']]],
  ['webdriversettings',['WebDriverSettings',['../class_alexander_on_test_1_1_web_driver_factory_nunit_config_1_1_test_settings_1_1_web_driver_settings.html',1,'AlexanderOnTest::WebDriverFactoryNunitConfig::TestSettings']]],
  ['windowdefinedsize',['WindowDefinedSize',['../interface_alexander_on_test_1_1_net_core_web_driver_factory_1_1_config_1_1_i_web_driver_configuration.html#ae19392489699a9c9e8710d4a5db7b49e',1,'AlexanderOnTest.NetCoreWebDriverFactory.Config.IWebDriverConfiguration.WindowDefinedSize()'],['../class_alexander_on_test_1_1_net_core_web_driver_factory_1_1_config_1_1_web_driver_configuration.html#a68a915d47cdac3db72bc42d2ba93f0b4',1,'AlexanderOnTest.NetCoreWebDriverFactory.Config.WebDriverConfiguration.WindowDefinedSize()']]],
  ['windows1803localwebdriverfactory',['Windows1803LocalWebDriverFactory',['../class_alexander_on_test_1_1_net_core_web_driver_factory_1_1_web_driver_factory_1_1_windows1803_local_web_driver_factory.html',1,'AlexanderOnTest.NetCoreWebDriverFactory.WebDriverFactory.Windows1803LocalWebDriverFactory'],['../class_alexander_on_test_1_1_net_core_web_driver_factory_1_1_web_driver_factory_1_1_windows1803_local_web_driver_factory.html#a73b87e738ee5129e3ad6a31e234d91ec',1,'AlexanderOnTest.NetCoreWebDriverFactory.WebDriverFactory.Windows1803LocalWebDriverFactory.Windows1803LocalWebDriverFactory(IDriverOptionsFactory driverOptionsFactory, string installedDriverPath, IWebDriverReSizer webDriverReSizer)'],['../class_alexander_on_test_1_1_net_core_web_driver_factory_1_1_web_driver_factory_1_1_windows1803_local_web_driver_factory.html#a62c6e2dfaeb0307deca438503442ba1b',1,'AlexanderOnTest.NetCoreWebDriverFactory.WebDriverFactory.Windows1803LocalWebDriverFactory.Windows1803LocalWebDriverFactory(IDriverOptionsFactory driverOptionsFactory, DriverPath driverPath, IWebDriverReSizer webDriverReSizer)']]],
  ['windowsize',['WindowSize',['../interface_alexander_on_test_1_1_net_core_web_driver_factory_1_1_config_1_1_i_web_driver_configuration.html#a0141e13480cf8614115ad262bd36db67',1,'AlexanderOnTest.NetCoreWebDriverFactory.Config.IWebDriverConfiguration.WindowSize()'],['../class_alexander_on_test_1_1_net_core_web_driver_factory_1_1_config_1_1_web_driver_configuration.html#a7a1b2a53069b07779759c14b9ef5d4cd',1,'AlexanderOnTest.NetCoreWebDriverFactory.Config.WebDriverConfiguration.WindowSize()'],['../class_alexander_on_test_1_1_web_driver_factory_nunit_config_1_1_test_settings_1_1_web_driver_settings.html#a75b11ac5107eb00e80935c7cd173198b',1,'AlexanderOnTest.WebDriverFactoryNunitConfig.TestSettings.WebDriverSettings.WindowSize()'],['../namespace_alexander_on_test_1_1_net_core_web_driver_factory.html#a60d35d89178cd99c8736665e2b7121fe',1,'AlexanderOnTest.NetCoreWebDriverFactory.WindowSize()']]],
  ['windowsizeextension',['WindowSizeExtension',['../class_alexander_on_test_1_1_net_core_web_driver_factory_1_1_window_size_extension.html',1,'AlexanderOnTest::NetCoreWebDriverFactory']]],
  ['withbrowser',['WithBrowser',['../class_alexander_on_test_1_1_net_core_web_driver_factory_1_1_utils_1_1_builders_1_1_web_driver_configuration_builder.html#a6313143945e5728683b697b2769a1703',1,'AlexanderOnTest::NetCoreWebDriverFactory::Utils::Builders::WebDriverConfigurationBuilder']]],
  ['withcustomsize',['WithCustomSize',['../class_alexander_on_test_1_1_net_core_web_driver_factory_1_1_utils_1_1_builders_1_1_web_driver_configuration_builder.html#ac1085c5b9b7fbb643e0f2b9035972509',1,'AlexanderOnTest::NetCoreWebDriverFactory::Utils::Builders::WebDriverConfigurationBuilder']]],
  ['withgriduri',['WithGridUri',['../class_alexander_on_test_1_1_net_core_web_driver_factory_1_1_utils_1_1_builders_1_1_web_driver_configuration_builder.html#a3a44201912647c041dbe6ce01f086277',1,'AlexanderOnTest::NetCoreWebDriverFactory::Utils::Builders::WebDriverConfigurationBuilder']]],
  ['withheadless',['WithHeadless',['../class_alexander_on_test_1_1_net_core_web_driver_factory_1_1_utils_1_1_builders_1_1_web_driver_configuration_builder.html#a907a48716e97d33620bc084fc23bfd98',1,'AlexanderOnTest::NetCoreWebDriverFactory::Utils::Builders::WebDriverConfigurationBuilder']]],
  ['withislocal',['WithIsLocal',['../class_alexander_on_test_1_1_net_core_web_driver_factory_1_1_utils_1_1_builders_1_1_web_driver_configuration_builder.html#a363c2c480a1aef6d8dde509e665e6dd2',1,'AlexanderOnTest::NetCoreWebDriverFactory::Utils::Builders::WebDriverConfigurationBuilder']]],
  ['withplatformtype',['WithPlatformType',['../class_alexander_on_test_1_1_net_core_web_driver_factory_1_1_utils_1_1_builders_1_1_web_driver_configuration_builder.html#acf35f732a2ededcad20f9d9545ea8fda',1,'AlexanderOnTest::NetCoreWebDriverFactory::Utils::Builders::WebDriverConfigurationBuilder']]],
  ['withwindowdefinedsize',['WithWindowDefinedSize',['../class_alexander_on_test_1_1_net_core_web_driver_factory_1_1_utils_1_1_builders_1_1_web_driver_configuration_builder.html#ad23e928ba7be7663f016847ffc0f8562',1,'AlexanderOnTest::NetCoreWebDriverFactory::Utils::Builders::WebDriverConfigurationBuilder']]],
  ['withwindowsize',['WithWindowSize',['../class_alexander_on_test_1_1_net_core_web_driver_factory_1_1_utils_1_1_builders_1_1_web_driver_configuration_builder.html#ae46169f0e813459b701e6f89a407ab0c',1,'AlexanderOnTest::NetCoreWebDriverFactory::Utils::Builders::WebDriverConfigurationBuilder']]],
  ['writejson',['WriteJson',['../class_alexander_on_test_1_1_net_core_web_driver_factory_1_1_utils_1_1_converters_1_1_size_json_converter.html#aa4a72bdd00b545521141b9d872b55451',1,'AlexanderOnTest::NetCoreWebDriverFactory::Utils::Converters::SizeJsonConverter']]]
];
